#         **PREMIER LEAGUE TABLE SQL PROJECT**

In [349]:
import csv, sqlite3
import sqlalchemy
import pandas as pd
import numpy as np
plt.style.use('default')

x = sqlite3.connect('PremierLeague.db')
cursorobj = x.cursor()

%reload_ext sql
%sql sqlite:///PremierLeague.db
    
df = pd.read_csv('allpltables.csv')
df.to_sql('allpltables', x, index=False, if_exists='replace', method='multi')

646

In [350]:
%%sql

SELECT * FROM 'allpltables'

 * sqlite:///PremierLeague.db
Done.

[('1992/93', 1, 'Manchester United', 42, 24, 12, 6, 67, 31, 36, 84),
 ('1992/93', 2, 'Aston Villa', 42, 21, 11, 10, 57, 40, 17, 74),
 ('1992/93', 3, 'Norwich City', 42, 21, 9, 12, 61, 65, -4, 72),
 ('1992/93', 4, 'Blackburn Rovers', 42, 20, 11, 11, 68, 46, 22, 71),
 ('1992/93', 5, 'Queens Park Rangers', 42, 17, 12, 13, 63, 55, 8, 63),
 ('1992/93', 6, 'Liverpool', 42, 16, 11, 15, 62, 55, 7, 59),
 ('1992/93', 7, 'Sheffield Wednesday', 42, 15, 14, 13, 55, 51, 4, 59),
 ('1992/93', 8, 'Tottenham Hotspur', 42, 16, 11, 15, 60, 66, -6, 59),
 ('1992/93', 9, 'Manchester City', 42, 15, 12, 15, 56, 51, 5, 57),
 ('1992/93', 10, 'Arsenal', 42, 15, 11, 16, 40, 38, 2, 56),
 ('1992/93', 11, 'Chelsea', 42, 14, 14, 14, 51, 54, -3, 56),
 ('1992/93', 12, 'Wimbledon', 42, 14, 12, 16, 56, 55, 1, 54),
 ('1992/93', 13, 'Everton', 42, 15, 8, 19, 53, 55, -2, 53),
 ('1992/93', 14, 'Sheffield United', 42, 14, 10, 18, 54, 53, 1, 52),
 ('1992/93', 15, 'Coventry City', 42, 13, 13, 16, 52, 57, -5, 52),
 ('1992/93', 16, 'Ipswich Town', 42, 12, 16, 14, 50, 55, -5, 52),
 ('1992/93', 17, 'Leeds United', 42, 12, 15, 15, 57, 62, -5, 51),
 ('1992/93', 18, 'Southampton', 42, 13, 11, 18, 54, 61, -7, 50),
 ('1992/93', 19, 'Oldham Athletic', 42, 13, 10, 19, 63, 74, -11, 49),
 ('1992/93', 20, 'Crystal Palace', 42, 11, 16, 15, 48, 61, -13, 49),
 ('1992/93', 21, 'Middlesbrough', 42, 11, 11, 20, 54, 75, -21, 44),
 ('1992/93', 22, 'Nottingham Forest', 42, 10, 10, 22, 41, 62, -21, 40),
 ('1993/94', 1, 'Manchester United', 42, 27, 11, 4, 80, 38, 42, 92),
 ('1993/94', 2, 'Blackburn Rovers', 42, 25, 9, 8, 63, 36, 27, 84),
 ('1993/94', 3, 'Newcastle United', 42, 23, 8, 11, 82, 41, 41, 77),
 ('1993/94', 4, 'Arsenal', 42, 18, 17, 7, 53, 28, 25, 71),
 ('1993/94', 5, 'Leeds United', 42, 18, 16, 8, 65, 39, 26, 70),
 ('1993/94', 6, 'Wimbledon', 42, 18, 11, 13, 56, 53, 3, 65),
 ('1993/94', 7, 'Sheffield Wednesday', 42, 16, 16, 10, 76, 54, 22, 64),
 ('1993/94', 8, 'Liverpool', 42, 17, 9, 16, 59, 55, 4, 60),
 ('1993/94', 9, 'Queens Park Rangers', 42, 16, 12, 14, 62, 61, 1, 60),
 ('1993/94', 10, 'Aston Villa', 42, 15, 12, 15, 46, 50, -4, 57),
 ('1993/94', 11, 'Coventry City', 42, 14, 14, 14, 43, 45, -2, 56),
 ('1993/94', 12, 'Norwich City', 42, 12, 17, 13, 65, 61, 4, 53),
 ('1993/94', 13, 'West Ham United', 42, 13, 13, 16, 47, 58, -11, 52),
 ('1993/94', 14, 'Chelsea', 42, 13, 12, 17, 49, 53, -4, 51),
 ('1993/94', 15, 'Tottenham Hotspur', 42, 11, 12, 19, 54, 59, -5, 45),
 ('1993/94', 16, 'Manchester City', 42, 9, 18, 15, 38, 49, -11, 45),
 ('1993/94', 17, 'Everton', 42, 12, 8, 22, 42, 63, -21, 44),
 ('1993/94', 18, 'Southampton', 42, 12, 7, 23, 49, 66, -17, 43),
 ('1993/94', 19, 'Ipswich Town', 42, 9, 16, 17, 35, 58, -23, 43),
 ('1993/94', 20, 'Sheffield United', 42, 8, 18, 16, 42, 60, -18, 42),
 ('1993/94', 21, 'Oldham Athletic', 42, 9, 13, 20, 42, 68, -26, 40),
 ('1993/94', 22, 'Swindon Town', 42, 5, 15, 22, 47, 100, -53, 30),
 ('1994/95', 1, 'Blackburn Rovers', 42, 27, 8, 7, 80, 39, 41, 89),
 ('1994/95', 2, 'Manchester United', 42, 26, 10, 6, 77, 29, 48, 88),
 ('1994/95', 3, 'Nottingham Forest', 42, 22, 11, 9, 72, 43, 29, 77),
 ('1994/95', 4, 'Liverpool', 42, 21, 11, 10, 65, 37, 28, 74),
 ('1994/95', 5, 'Leeds United', 42, 20, 13, 9, 59, 38, 21, 73),
 ('1994/95', 6, 'Newcastle United', 42, 20, 12, 10, 67, 47, 20, 72),
 ('1994/95', 7, 'Tottenham Hotspur', 42, 16, 14, 12, 66, 58, 8, 62),
 ('1994/95', 8, 'Queens Park Rangers', 42, 17, 9, 16, 61, 59, 2, 60),
 ('1994/95', 9, 'Wimbledon', 42, 15, 11, 16, 48, 65, -17, 56),
 ('1994/95', 10, 'Southampton', 42, 12, 18, 12, 61, 63, -2, 54),
 ('1994/95', 11, 'Chelsea', 42, 13, 15, 14, 50, 55, -5, 54),
 ('1994/95', 12, 'Arsenal', 42, 13, 12, 17, 53, 49, 4, 51),
 ('1994/95', 13, 'Sheffield Wednesday', 42, 13, 12, 17, 49, 57, -8, 51),
 ('1994/95', 14, 'West Ham United', 42, 13, 11, 18, 44, 48, -4, 50),
 ('1994/95', 15, 'Everton', 42, 11, 17, 14, 44, 51, -7, 50),
 ('1994/95', 16, 'Coventry City', 42, 12, 14, 16, 44, 62, -18, 50),
 ('1994/95', 17, 'Manchester City', 42, 12, 13, 17, 53, 64, -11, 49),
 ('1994/95', 18, 'Aston Villa', 42, 11, 15, 16, 51, 56, -5, 48),
 ('1994/95', 19, 'Crystal Palace', 42, 11, 12, 19, 34, 49, -15, 45),
 ('1994/95', 20, 'Norwich City', 42, 10, 13, 19, 37, 54, -17, 43),
 ('1994/95', 21, 'Leicester City', 42, 6, 11, 25, 45, 80, -35, 29),
 ('1994/95', 22, 'Ipswich Town', 42, 7, 6, 29, 36, 93, -57, 27),
 ('1995/96', 1, 'Manchester United', 38, 25, 7, 6, 73, 35, 38, 82),
 ('1995/96', 2, 'Newcastle United', 38, 24, 6, 8, 66, 37, 29, 78),
 ('1995/96', 3, 'Liverpool', 38, 20, 11, 7, 70, 34, 36, 71),
 ('1995/96', 4, 'Aston Villa', 38, 18, 9, 11, 52, 35, 17, 63),
 ('1995/96', 5, 'Arsenal', 38, 17, 12, 9, 49, 32, 17, 63),
 ('1995/96', 6, 'Everton', 38, 17, 10, 11, 64, 44, 20, 61),
 ('1995/96', 7, 'Blackburn Rovers', 38, 18, 7, 13, 61, 47, 14, 61),
 ('1995/96', 8, 'Tottenham Hotspur', 38, 16, 13, 9, 50, 38, 12, 61),
 ('1995/96', 9, 'Nottingham Forest', 38, 15, 13, 10, 50, 54, -4, 58),
 ('1995/96', 10, 'West Ham United', 38, 14, 9, 15, 43, 52, -9, 51),
 ('1995/96', 11, 'Chelsea', 38, 12, 14, 12, 46, 44, 2, 50),
 ('1995/96', 12, 'Middlesbrough', 38, 11, 10, 17, 35, 50, -15, 43),
 ('1995/96', 13, 'Leeds United', 38, 12, 7, 19, 40, 57, -17, 43),
 ('1995/96', 14, 'Wimbledon', 38, 10, 11, 17, 55, 70, -15, 41),
 ('1995/96', 15, 'Sheffield Wednesday', 38, 10, 10, 18, 48, 61, -13, 40),
 ('1995/96', 16, 'Coventry City', 38, 8, 14, 16, 42, 60, -18, 38),
 ('1995/96', 17, 'Southampton', 38, 9, 11, 18, 34, 52, -18, 38),
 ('1995/96', 18, 'Manchester City', 38, 9, 11, 18, 33, 58, -25, 38),
 ('1995/96', 19, 'Queens Park Rangers', 38, 9, 6, 23, 38, 57, -19, 33),
 ('1995/96', 20, 'Bolton Wanderers', 38, 8, 5, 25, 39, 71, -32, 29),
 ('1996/97', 1, 'Manchester United', 38, 21, 12, 5, 76, 44, 32, 75),
 ('1996/97', 2, 'Newcastle United', 38, 19, 11, 8, 73, 40, 33, 68),
 ('1996/97', 3, 'Arsenal', 38, 19, 11, 8, 62, 32, 30, 68),
 ('1996/97', 4, 'Liverpool', 38, 19, 11, 8, 62, 37, 25, 68),
 ('1996/97', 5, 'Aston Villa', 38, 17, 10, 11, 47, 34, 13, 61),
 ('1996/97', 6, 'Chelsea', 38, 16, 11, 11, 58, 55, 3, 59),
 ('1996/97', 7, 'Sheffield Wednesday', 38, 14, 15, 9, 50, 51, -1, 57),
 ('1996/97', 8, 'Wimbledon', 38, 15, 11, 12, 49, 46, 3, 56),
 ('1996/97', 9, 'Leicester City', 38, 12, 11, 15, 46, 54, -8, 47),
 ('1996/97', 10, 'Tottenham Hotspur', 38, 13, 7, 18, 44, 51, -7, 46),
 ('1996/97', 11, 'Leeds United', 38, 11, 13, 14, 28, 38, -10, 46),
 ('1996/97', 12, 'Derby County', 38, 11, 13, 14, 45, 58, -13, 46),
 ('1996/97', 13, 'Blackburn Rovers', 38, 9, 15, 14, 42, 43, -1, 42),
 ('1996/97', 14, 'West Ham United', 38, 10, 12, 16, 39, 48, -9, 42),
 ('1996/97', 15, 'Everton', 38, 10, 12, 16, 44, 57, -13, 42),
 ('1996/97', 16, 'Southampton', 38, 10, 11, 17, 50, 56, -6, 41),
 ('1996/97', 17, 'Coventry City', 38, 9, 14, 15, 38, 54, -16, 41),
 ('1996/97', 18, 'Sunderland', 38, 10, 10, 18, 35, 53, -18, 40),
 ('1996/97', 19, 'Middlesbrough', 38, 10, 12, 16, 51, 60, -9, 39),
 ('1996/97', 20, 'Nottingham Forest', 38, 6, 16, 16, 31, 59, -28, 34),
 ('1997/98', 1, 'Arsenal', 38, 23, 9, 6, 68, 33, 35, 78),
 ('1997/98', 2, 'Manchester United', 38, 23, 8, 7, 73, 26, 47, 77),
 ('1997/98', 3, 'Liverpool', 38, 18, 11, 9, 68, 42, 26, 65),
 ('1997/98', 4, 'Chelsea', 38, 20, 3, 15, 71, 43, 28, 63),
 ('1997/98', 5, 'Leeds United', 38, 17, 8, 13, 57, 46, 11, 59),
 ('1997/98', 6, 'Blackburn Rovers', 38, 16, 10, 12, 57, 52, 5, 58),
 ('1997/98', 7, 'Aston Villa', 38, 17, 6, 15, 49, 48, 1, 57),
 ('1997/98', 8, 'West Ham United', 38, 16, 8, 14, 56, 57, -1, 56),
 ('1997/98', 9, 'Derby County', 38, 16, 7, 15, 52, 49, 3, 55),
 ('1997/98', 10, 'Leicester City', 38, 13, 14, 11, 51, 41, 10, 53),
 ('1997/98', 11, 'Coventry City', 38, 12, 16, 10, 46, 44, 2, 52),
 ('1997/98', 12, 'Southampton', 38, 14, 6, 18, 50, 55, -5, 48),
 ('1997/98', 13, 'Newcastle United', 38, 11, 11, 16, 35, 44, -9, 44),
 ('1997/98', 14, 'Tottenham Hotspur', 38, 11, 11, 16, 44, 56, -12, 44),
 ('1997/98', 15, 'Wimbledon', 38, 10, 14, 14, 34, 46, -12, 44),
 ('1997/98', 16, 'Sheffield Wednesday', 38, 12, 8, 18, 52, 67, -15, 44),
 ('1997/98', 17, 'Everton', 38, 9, 13, 16, 41, 56, -15, 40),
 ('1997/98', 18, 'Bolton Wanderers', 38, 9, 13, 16, 41, 61, -20, 40),
 ('1997/98', 19, 'Barnsley', 38, 10, 5, 23, 37, 82, -45, 35),
 ('1997/98', 20, 'Crystal Palace', 38, 8, 9, 21, 37, 71, -34, 33),
 ('1998/99', 1, 'Manchester United', 38, 22, 13, 3, 80, 37, 43, 79),
 ('1998/99', 2, 'Arsenal', 38, 22, 12, 4, 59, 17, 42, 78),
 ('1998/99', 3, 'Chelsea', 38, 20, 15, 3, 57, 30, 27, 75),
 ('1998/99', 4, 'Leeds United', 38, 18, 13, 7, 62, 34, 28, 67),
 ('1998/99', 5, 'West Ham United', 38, 16, 9, 13, 46, 53, -7, 57),
 ('1998/99', 6, 'Aston Villa', 38, 15, 10, 13, 51, 46, 5, 55),
 ('1998/99', 7, 'Liverpool', 38, 15, 9, 14, 68, 49, 19, 54),
 ('1998/99', 8, 'Derby County', 38, 13, 13, 12, 40, 45, -5, 52),
 ('1998/99', 9, 'Middlesbrough', 38, 12, 15, 11, 48, 54, -6, 51),
 ('1998/99', 10, 'Leicester City', 38, 12, 13, 13, 40, 46, -6, 49),
 ('1998/99', 11, 'Tottenham Hotspur', 38, 11, 14, 13, 47, 50, -3, 47),
 ('1998/99', 12, 'Sheffield Wednesday', 38, 13, 7, 18, 41, 42, -1, 46),
 ('1998/99', 13, 'Newcastle United', 38, 11, 13, 14, 48, 54, -6, 46),
 ('1998/99', 14, 'Everton', 38, 11, 10, 17, 42, 47, -5, 43),
 ('1998/99', 15, 'Coventry City', 38, 11, 9, 18, 39, 51, -12, 42),
 ('1998/99', 16, 'Wimbledon', 38, 10, 12, 16, 40, 63, -23, 42),
 ('1998/99', 17, 'Southampton', 38, 11, 8, 19, 37, 64, -27, 41),
 ('1998/99', 18, 'Charlton Ath', 38, 8, 12, 18, 41, 56, -15, 36),
 ('1998/99', 19, 'Blackburn Rovers', 38, 7, 14, 17, 38, 52, -14, 35),
 ('1998/99', 20, 'Nottingham Forest', 38, 7, 9, 22, 35, 69, -34, 30),
 ('1999/2000', 1, 'Manchester United', 38, 28, 7, 3, 97, 45, 52, 91),
 ('1999/2000', 2, 'Arsenal', 38, 22, 7, 9, 73, 43, 30, 73),
 ('1999/2000', 3, 'Leeds United', 38, 21, 6, 11, 58, 43, 15, 69),
 ('1999/2000', 4, 'Liverpool', 38, 19, 10, 9, 51, 30, 21, 67),
 ('1999/2000', 5, 'Chelsea', 38, 18, 11, 9, 53, 34, 19, 65),
 ('1999/2000', 6, 'Aston Villa', 38, 15, 13, 10, 46, 35, 11, 58),
 ('1999/2000', 7, 'Sunderland', 38, 16, 10, 12, 57, 56, 1, 58),
 ('1999/2000', 8, 'Leicester City', 38, 16, 7, 15, 55, 55, 0, 55),
 ('1999/2000', 9, 'West Ham United', 38, 15, 10, 13, 52, 53, -1, 55),
 ('1999/2000', 10, 'Tottenham Hotspur', 38, 15, 8, 15, 57, 49, 8, 53),
 ('1999/2000', 11, 'Newcastle United', 38, 14, 10, 14, 63, 54, 9, 52),
 ('1999/2000', 12, 'Middlesbrough', 38, 14, 10, 14, 46, 52, -6, 52),
 ('1999/2000', 13, 'Everton', 38, 12, 14, 12, 59, 49, 10, 50),
 ('1999/2000', 14, 'Coventry City', 38, 12, 8, 18, 47, 54, -7, 44),
 ('1999/2000', 15, 'Southampton', 38, 12, 8, 18, 45, 62, -17, 44),
 ('1999/2000', 16, 'Derby County', 38, 9, 11, 18, 44, 57, -13, 38),
 ('1999/2000', 17, 'Bradford City', 38, 9, 9, 20, 38, 68, -30, 36),
 ('1999/2000', 18, 'Wimbledon', 38, 7, 12, 19, 46, 74, -28, 33),
 ('1999/2000', 19, 'Sheffield Wednesday', 38, 8, 7, 23, 38, 70, -32, 31),
 ('1999/2000', 20, 'Watford', 38, 6, 6, 26, 35, 77, -42, 24),
 ('2000/01', 1, 'Manchester United', 38, 24, 8, 6, 79, 31, 48, 80),
 ('2000/01', 2, 'Arsenal', 38, 20, 10, 8, 63, 38, 25, 70),
 ('2000/01', 3, 'Liverpool', 38, 20, 9, 9, 71, 39, 32, 69),
 ('2000/01', 4, 'Leeds United', 38, 20, 8, 10, 64, 43, 21, 68),
 ('2000/01', 5, 'Ipswich Town', 38, 20, 6, 12, 57, 42, 15, 66),
 ('2000/01', 6, 'Chelsea', 38, 17, 10, 11, 68, 45, 23, 61),
 ('2000/01', 7, 'Sunderland', 38, 15, 12, 11, 46, 41, 5, 57),
 ('2000/01', 8, 'Aston Villa', 38, 13, 15, 10, 46, 43, 3, 54),
 ('2000/01', 9, 'Charlton Ath', 38, 14, 10, 14, 50, 57, -7, 52),
 ('2000/01', 10, 'Southampton', 38, 14, 10, 14, 40, 48, -8, 52),
 ('2000/01', 11, 'Newcastle United', 38, 14, 9, 15, 44, 50, -6, 51),
 ('2000/01', 12, 'Tottenham Hotspur', 38, 13, 10, 15, 47, 54, -7, 49),
 ('2000/01', 13, 'Leicester City', 38, 14, 6, 18, 39, 51, -12, 48),
 ('2000/01', 14, 'Middlesbrough', 38, 9, 15, 14, 44, 44, 0, 42),
 ('2000/01', 15, 'West Ham United', 38, 10, 12, 16, 45, 50, -5, 42),
 ('2000/01', 16, 'Everton', 38, 11, 9, 18, 45, 59, -14, 42),
 ('2000/01', 17, 'Derby County', 38, 10, 12, 16, 37, 59, -22, 42),
 ('2000/01', 18, 'Manchester City', 38, 8, 10, 20, 41, 65, -24, 34),
 ('2000/01', 19, 'Coventry City', 38, 8, 10, 20, 36, 63, -27, 34),
 ('2000/01', 20, 'Bradford City', 38, 5, 11, 22, 30, 70, -40, 26),
 ('2001/02', 1, 'Arsenal', 38, 26, 9, 3, 79, 36, 43, 87),
 ('2001/02', 2, 'Liverpool', 38, 24, 8, 6, 67, 30, 37, 80),
 ('2001/02', 3, 'Manchester United', 38, 24, 5, 9, 87, 45, 42, 77),
 ('2001/02', 4, 'Newcastle United', 38, 21, 8, 9, 74, 52, 22, 71),
 ('2001/02', 5, 'Leeds United', 38, 18, 12, 8, 53, 37, 16, 66),
 ('2001/02', 6, 'Chelsea', 38, 17, 13, 8, 66, 38, 28, 64),
 ('2001/02', 7, 'West Ham United', 38, 15, 8, 15, 48, 57, -9, 53),
 ('2001/02', 8, 'Aston Villa', 38, 12, 14, 12, 46, 47, -1, 50),
 ('2001/02', 9, 'Tottenham Hotspur', 38, 14, 8, 16, 49, 53, -4, 50),
 ('2001/02', 10, 'Blackburn Rovers', 38, 12, 10, 16, 55, 51, 4, 46),
 ('2001/02', 11, 'Southampton', 38, 12, 9, 17, 46, 54, -8, 45),
 ('2001/02', 12, 'Middlesbrough', 38, 12, 9, 17, 35, 47, -12, 45),
 ('2001/02', 13, 'Fulham', 38, 10, 14, 14, 36, 44, -8, 44),
 ('2001/02', 14, 'Charlton Ath', 38, 10, 14, 14, 38, 49, -11, 44),
 ('2001/02', 15, 'Everton', 38, 11, 10, 17, 45, 57, -12, 43),
 ('2001/02', 16, 'Bolton Wanderers', 38, 9, 13, 16, 44, 62, -18, 40),
 ('2001/02', 17, 'Sunderland', 38, 10, 10, 18, 29, 51, -22, 40),
 ('2001/02', 18, 'Ipswich Town', 38, 9, 9, 20, 41, 64, -23, 36),
 ('2001/02', 19, 'Derby County', 38, 8, 6, 24, 33, 63, -30, 30),
 ('2001/02', 20, 'Leicester City', 38, 5, 13, 20, 30, 64, -34, 28),
 ('2002/03', 1, 'Manchester United', 38, 25, 8, 5, 74, 34, 40, 83),
 ('2002/03', 2, 'Arsenal', 38, 23, 9, 6, 85, 42, 43, 78),
 ('2002/03', 3, 'Newcastle United', 38, 21, 6, 11, 63, 48, 15, 69),
 ('2002/03', 4, 'Chelsea', 38, 19, 10, 9, 68, 38, 30, 67),
 ('2002/03', 5, 'Liverpool', 38, 18, 10, 10, 61, 41, 20, 64),
 ('2002/03', 6, 'Blackburn Rovers', 38, 16, 12, 10, 52, 43, 9, 60),
 ('2002/03', 7, 'Everton', 38, 17, 8, 13, 48, 49, -1, 59),
 ('2002/03', 8, 'Southampton', 38, 13, 13, 12, 43, 46, -3, 52),
 ('2002/03', 9, 'Manchester City', 38, 15, 6, 17, 47, 54, -7, 51),
 ('2002/03', 10, 'Tottenham Hotspur', 38, 14, 8, 16, 51, 62, -11, 50),
 ('2002/03', 11, 'Middlesbrough', 38, 13, 10, 15, 48, 44, 4, 49),
 ('2002/03', 12, 'Charlton Ath', 38, 14, 7, 17, 45, 56, -11, 49),
 ('2002/03', 13, 'Birmingham City', 38, 13, 9, 16, 41, 49, -8, 48),
 ('2002/03', 14, 'Fulham', 38, 13, 9, 16, 41, 50, -9, 48),
 ('2002/03', 15, 'Leeds United', 38, 14, 5, 19, 58, 57, 1, 47),
 ('2002/03', 16, 'Aston Villa', 38, 12, 9, 17, 42, 47, -5, 45),
 ('2002/03', 17, 'Bolton Wanderers', 38, 10, 14, 14, 41, 51, -10, 44),
 ('2002/03', 18, 'West Ham United', 38, 10, 12, 16, 42, 59, -17, 42),
 ('2002/03', 19, 'West Bromwich Albion', 38, 6, 8, 24, 29, 65, -36, 26),
 ('2002/03', 20, 'Sunderland', 38, 4, 7, 27, 21, 65, -44, 19),
 ('2003/04', 1, 'Arsenal', 38, 26, 12, 0, 73, 26, 47, 90),
 ('2003/04', 2, 'Chelsea', 38, 24, 7, 7, 67, 30, 37, 79),
 ('2003/04', 3, 'Manchester United', 38, 23, 6, 9, 64, 35, 29, 75),
 ('2003/04', 4, 'Liverpool', 38, 16, 12, 10, 55, 37, 18, 60),
 ('2003/04', 5, 'Newcastle United', 38, 13, 17, 8, 52, 40, 12, 56),
 ('2003/04', 6, 'Aston Villa', 38, 15, 11, 12, 48, 44, 4, 56),
 ('2003/04', 7, 'Charlton Ath', 38, 14, 11, 13, 51, 51, 0, 53),
 ('2003/04', 8, 'Bolton Wanderers', 38, 14, 11, 13, 48, 56, -8, 53),
 ('2003/04', 9, 'Fulham', 38, 14, 10, 14, 52, 46, 6, 52),
 ('2003/04', 10, 'Birmingham City', 38, 12, 14, 12, 43, 48, -5, 50),
 ('2003/04', 11, 'Middlesbrough', 38, 13, 9, 16, 44, 52, -8, 48),
 ('2003/04', 12, 'Southampton', 38, 12, 11, 15, 44, 45, -1, 47),
 ('2003/04', 13, 'Portsmouth', 38, 12, 9, 17, 47, 54, -7, 45),
 ('2003/04', 14, 'Tottenham Hotspur', 38, 13, 6, 19, 47, 57, -10, 45),
 ('2003/04', 15, 'Blackburn Rovers', 38, 12, 8, 18, 51, 59, -8, 44),
 ('2003/04', 16, 'Manchester City', 38, 9, 14, 15, 55, 54, 1, 41),
 ('2003/04', 17, 'Everton', 38, 9, 12, 17, 45, 57, -12, 39),
 ('2003/04', 18, 'Leicester City', 38, 6, 15, 17, 48, 65, -17, 33),
 ('2003/04', 19, 'Leeds United', 38, 8, 9, 21, 40, 79, -39, 33),
 ('2003/04', 20, 'Wolverhampton Wanderers', 38, 7, 12, 19, 38, 77, -39, 33),
 ('2004/05', 1, 'Chelsea', 38, 29, 8, 1, 72, 15, 57, 95),
 ('2004/05', 2, 'Arsenal', 38, 25, 8, 5, 87, 36, 51, 83),
 ('2004/05', 3, 'Manchester United', 38, 22, 11, 5, 58, 26, 32, 77),
 ('2004/05', 4, 'Everton', 38, 18, 7, 13, 45, 46, -1, 61),
 ('2004/05', 5, 'Liverpool', 38, 17, 7, 14, 52, 41, 11, 58),
 ('2004/05', 6, 'Bolton Wanderers', 38, 16, 10, 12, 49, 44, 5, 58),
 ('2004/05', 7, 'Middlesbrough', 38, 14, 13, 11, 53, 46, 7, 55),
 ('2004/05', 8, 'Manchester City', 38, 13, 13, 12, 47, 39, 8, 52),
 ('2004/05', 9, 'Tottenham Hotspur', 38, 14, 10, 14, 47, 41, 6, 52),
 ('2004/05', 10, 'Aston Villa', 38, 12, 11, 15, 45, 52, -7, 47),
 ('2004/05', 11, 'Charlton Ath', 38, 12, 10, 16, 42, 58, -16, 46),
 ('2004/05', 12, 'Birmingham City', 38, 11, 12, 15, 40, 46, -6, 45),
 ('2004/05', 13, 'Fulham', 38, 12, 8, 18, 52, 60, -8, 44),
 ('2004/05', 14, 'Newcastle United', 38, 10, 14, 14, 47, 57, -10, 44),
 ('2004/05', 15, 'Blackburn Rovers', 38, 9, 15, 14, 32, 43, -11, 42),
 ('2004/05', 16, 'Portsmouth', 38, 10, 9, 19, 43, 59, -16, 39),
 ('2004/05', 17, 'West Bromwich Albion', 38, 6, 16, 16, 36, 61, -25, 34),
 ('2004/05', 18, 'Crystal Palace', 38, 7, 12, 19, 41, 62, -21, 33),
 ('2004/05', 19, 'Norwich City', 38, 7, 12, 19, 42, 77, -35, 33),
 ('2004/05', 20, 'Southampton', 38, 6, 14, 18, 45, 66, -21, 32),
 ('2005/06', 1, 'Chelsea', 38, 29, 4, 5, 72, 22, 50, 91),
 ('2005/06', 2, 'Manchester United', 38, 25, 8, 5, 72, 34, 38, 83),
 ('2005/06', 3, 'Liverpool', 38, 25, 7, 6, 57, 25, 32, 82),
 ('2005/06', 4, 'Arsenal', 38, 20, 7, 11, 68, 31, 37, 67),
 ('2005/06', 5, 'Tottenham Hotspur', 38, 18, 11, 9, 53, 38, 15, 65),
 ('2005/06', 6, 'Blackburn Rovers', 38, 19, 6, 13, 51, 42, 9, 63),
 ('2005/06', 7, 'Newcastle United', 38, 17, 7, 14, 47, 42, 5, 58),
 ('2005/06', 8, 'Bolton Wanderers', 38, 15, 11, 12, 49, 41, 8, 56),
 ('2005/06', 9, 'West Ham United', 38, 16, 7, 15, 52, 55, -3, 55),
 ('2005/06', 10, 'Wigan Athletic', 38, 15, 6, 17, 45, 52, -7, 51),
 ('2005/06', 11, 'Everton', 38, 14, 8, 16, 34, 49, -15, 50),
 ('2005/06', 12, 'Fulham', 38, 14, 6, 18, 48, 58, -10, 48),
 ('2005/06', 13, 'Charlton Ath', 38, 13, 8, 17, 41, 55, -14, 47),
 ('2005/06', 14, 'Middlesbrough', 38, 12, 9, 17, 48, 58, -10, 45),
 ('2005/06', 15, 'Manchester City', 38, 13, 4, 21, 43, 48, -5, 43),
 ('2005/06', 16, 'Aston Villa', 38, 10, 12, 16, 42, 55, -13, 42),
 ('2005/06', 17, 'Portsmouth', 38, 10, 8, 20, 37, 62, -25, 38),
 ('2005/06', 18, 'Birmingham City', 38, 8, 10, 20, 28, 50, -22, 34),
 ('2005/06', 19, 'West Bromwich Albion', 38, 7, 9, 22, 31, 58, -27, 30),
 ('2005/06', 20, 'Sunderland', 38, 3, 6, 29, 26, 69, -43, 15),
 ('2006/07', 1, 'Manchester United', 38, 28, 5, 5, 83, 27, 56, 89),
 ('2006/07', 2, 'Chelsea', 38, 24, 11, 3, 64, 24, 40, 83),
 ('2006/07', 3, 'Liverpool', 38, 20, 8, 10, 57, 27, 30, 68),
 ('2006/07', 4, 'Arsenal', 38, 19, 11, 8, 63, 35, 28, 68),
 ('2006/07', 5, 'Tottenham Hotspur', 38, 17, 9, 12, 57, 54, 3, 60),
 ('2006/07', 6, 'Everton', 38, 15, 13, 10, 52, 36, 16, 58),
 ('2006/07', 7, 'Bolton Wanderers', 38, 16, 8, 14, 47, 52, -5, 56),
 ('2006/07', 8, 'Reading', 38, 16, 7, 15, 52, 47, 5, 55),
 ('2006/07', 9, 'Portsmouth', 38, 14, 12, 12, 45, 42, 3, 54),
 ('2006/07', 10, 'Blackburn Rovers', 38, 15, 7, 16, 52, 54, -2, 52),
 ('2006/07', 11, 'Aston Villa', 38, 11, 17, 10, 43, 41, 2, 50),
 ('2006/07', 12, 'Middlesbrough', 38, 12, 10, 16, 44, 49, -5, 46),
 ('2006/07', 13, 'Newcastle United', 38, 11, 10, 17, 38, 47, -9, 43),
 ('2006/07', 14, 'Manchester City', 38, 11, 9, 18, 29, 44, -15, 42),
 ('2006/07', 15, 'West Ham United', 38, 12, 5, 21, 35, 59, -24, 41),
 ('2006/07', 16, 'Fulham', 38, 8, 15, 15, 38, 60, -22, 39),
 ('2006/07', 17, 'Wigan Athletic', 38, 10, 8, 20, 37, 59, -22, 38),
 ('2006/07', 18, 'Sheffield United', 38, 10, 8, 20, 32, 55, -23, 38),

# TEAM WITH THE MOST TITLES IN PL HISTORY:

In [354]:
%%sql

SELECT TEAM, count(TEAM) AS 'NUMBER OF TITLES WON'
FROM 'allpltables'
WHERE POSITION = 1
GROUP BY TEAM
ORDER BY count(TEAM) DESC
LIMIT 1;

 * sqlite:///PremierLeague.db
Done.

[('Manchester United', 13)]

# TEAM WITH THE MOST POINTS IN PL HISTORY:

In [356]:
%%sql

SELECT TEAM, SUM("POINTS") AS 'NUMBER OF POINTS'
FROM 'allpltables'
GROUP BY TEAM
ORDER BY SUM("POINTS") DESC
LIMIT 1;

 * sqlite:///PremierLeague.db
Done.

[('Manchester United', 2501)]

# TEAM WITH THE LEAST AMOUNT OF POINTS IN PL HISTORY:

In [323]:
%%sql

SELECT TEAM, SUM("POINTS") AS 'NUMBER OF POINTS'
FROM 'allpltables'
GROUP BY TEAM
ORDER BY SUM("POINTS")
LIMIT 1;

 * sqlite:///PremierLeague.db
Done.

[('Luton Town', 26)]

# RECORD FOR MOST POINTS IN  A SINGLE SEASON:

In [324]:
%%sql

SELECT TEAM, MAX(POINTS) AS 'POINTS', SEASON
FROM 'allpltables';

 * sqlite:///PremierLeague.db
Done.

[('Manchester City', 100, '2017/18')]

# RECORD FOR LEAST POINTS IN  A SINGLE SEASON:

In [325]:
%%sql

SELECT TEAM, MIN(POINTS) AS 'POINTS', SEASON
FROM 'allpltables';

 * sqlite:///PremierLeague.db
Done.

[('Derby County', 11, '2007/08')]

# WENT THROUGH AN ENTIRE SEASON UNBEATEN:

In [326]:
%%sql

SELECT TEAM, LOSSES, SEASON
FROM 'allpltables'
WHERE LOSSES = 0;

 * sqlite:///PremierLeague.db
Done.

[('Arsenal', 0, '2003/04')]

# NUMBER OF WINS IN PL HISTORY:

In [327]:
%%sql

SELECT TEAM, SUM("WINS") AS 'NUMBER OF WINS'
FROM 'allpltables'
GROUP BY TEAM
ORDER BY SUM("WINS") DESC
LIMIT 1;

 * sqlite:///PremierLeague.db
Done.

[('Manchester United', 744)]

# LEAST NUMBER OF WINS IN PL HISTORY:

In [328]:
%%sql

SELECT TEAM, SUM("WINS") AS 'NUMBER OF WINS'
FROM 'allpltables'
GROUP BY TEAM
ORDER BY SUM("WINS")
LIMIT 1;

 * sqlite:///PremierLeague.db
Done.

[('Swindon Town', 5)]

# MOST LOSSES IN PL HISTORY:

In [329]:
%%sql

SELECT TEAM, SUM("LOSSES") AS 'NUMBER OF LOSSES'
FROM 'allpltables'
GROUP BY TEAM
ORDER BY SUM("LOSSES") DESC
LIMIT 1;

 * sqlite:///PremierLeague.db
Done.

[('Everton', 448)]

# LEAST NUMBER OF LOSSES IN PL HISTORY:

In [330]:
%%sql

SELECT TEAM, SUM("LOSSES") AS 'NUMBER OF LOSSES'
FROM 'allpltables'
GROUP BY TEAM
ORDER BY SUM("LOSSES")
LIMIT 1;

 * sqlite:///PremierLeague.db
Done.

[('Blackpool', 19)]

# RELEGATED THE MOST IN PL HISTORY:

In [331]:
%%sql

SELECT TEAM, count(TEAM) AS 'NUMBER OF RELEGATIONS'
FROM 'allpltables'
WHERE POSITION BETWEEN 18 and 22
GROUP BY TEAM
ORDER BY count(TEAM) DESC
LIMIT 1;

 * sqlite:///PremierLeague.db
Done.

[('Norwich City', 6)]

# MOST GOALS SCORED IN PL HISTORY:

In [333]:
%%sql

SELECT TEAM, SUM("GOALS FOR") AS 'NUMBER OF GOALS SCORED'
FROM 'allpltables'
GROUP BY TEAM
ORDER BY SUM("GOALS FOR") DESC
LIMIT 1;

 * sqlite:///PremierLeague.db
Done.

[('Manchester United', 2300)]

# MOST GOALS SCORED IN A SINGLE SEASON:

In [332]:
%%sql

SELECT TEAM, MAX("GOALS FOR") AS 'NUMBER OF GOALS SCORED', SEASON
FROM 'allpltables';

 * sqlite:///PremierLeague.db
Done.

[('Manchester City', 106, '2017/18')]

# LEAST GOALS SCORED IN PL HISTORY:

In [334]:
%%sql

SELECT TEAM, SUM("GOALS FOR") AS 'NUMBER OF GOALS SCORED'
FROM 'allpltables'
GROUP BY TEAM
ORDER BY SUM("GOALS FOR")
LIMIT 1;

 * sqlite:///PremierLeague.db
Done.

[('Barnsley', 37)]

# LEAST GOALS SCORED IN A SINGLE SEASON:

In [335]:
%%sql

SELECT TEAM, MIN("GOALS FOR") AS 'NUMBER OF GOALS SCORED', SEASON
FROM 'allpltables';

 * sqlite:///PremierLeague.db
Done.

[('Derby County', 20, '2007/08')]

# MOST GOALS CONCEDED IN PL HISTORY:

In [339]:
%%sql

SELECT TEAM, SUM("GOALS AGAINST") AS 'NUMBER OF GOALS CONCEDED'
FROM 'allpltables'
GROUP BY TEAM
ORDER BY SUM("GOALS AGAINST") DESC
LIMIT 1;

 * sqlite:///PremierLeague.db
Done.

[('Everton', 1589)]

# LEAST GOALS CONCEDED IN PL HISTORY:

In [340]:
%%sql

SELECT TEAM, SUM("GOALS AGAINST") AS 'NUMBER OF GOALS CONCEDED'
FROM 'allpltables'
GROUP BY TEAM
ORDER BY SUM("GOALS AGAINST")
LIMIT 1;

 * sqlite:///PremierLeague.db
Done.

[('Blackpool', 78)]

# HIGHEST GOAL DIFFERENCE IN PL HISTORY:

In [342]:
%%sql

SELECT TEAM, SUM("GOAL DIFFERENCE") AS 'GOAL DIFFERENCE TALLY'
FROM 'allpltables'
GROUP BY TEAM
ORDER BY SUM("GOAL DIFFERENCE") DESC
LIMIT 1;

 * sqlite:///PremierLeague.db
Done.

[('Manchester United', 1132)]

# LOWEST GOAL DIFFERENCE IN PL HISTORY:

In [341]:
%%sql

SELECT TEAM, SUM("GOAL DIFFERENCE") AS 'GOAL DIFFERENCE TALLY'
FROM 'allpltables'
GROUP BY TEAM
ORDER BY SUM("GOAL DIFFERENCE")
LIMIT 1;

 * sqlite:///PremierLeague.db
Done.

[('Sunderland', -292)]

# ALL TIME PREMIER LEAGUE TABLE:

In [343]:
%%sql

SELECT
TEAM, 
SUM(MATCHES) AS MATCHES,
SUM(WINS) AS WINS, 
SUM(DRAWS)AS DRAWS, 
SUM(LOSSES) AS LOSSES, 
SUM("GOALS FOR") AS "GOALS FOR", 
SUM("GOALS AGAINST") AS "GOALS AGAINST", 
SUM("GOAL DIFFERENCE") AS "GOAL DIFFERENCE", 
SUM(POINTS) AS POINTS

FROM 'allpltables'
GROUP BY TEAM
ORDER BY SUM(POINTS) DESC;

 * sqlite:///PremierLeague.db
Done.

[('Manchester United', 1228, 744, 269, 215, 2300, 1168, 1132, 2501),
 ('Arsenal', 1228, 673, 295, 260, 2197, 1220, 977, 2314),
 ('Liverpool', 1228, 652, 302, 274, 2182, 1235, 947, 2258),
 ('Chelsea', 1228, 647, 304, 277, 2088, 1235, 853, 2245),
 ('Tottenham Hotspur', 1228, 540, 293, 395, 1889, 1562, 327, 1913),
 ('Manchester City', 1038, 529, 222, 287, 1848, 1135, 713, 1809),
 ('Everton', 1228, 439, 341, 448, 1565, 1589, -24, 1650),
 ('Newcastle United', 1110, 419, 284, 407, 1530, 1512, 18, 1541),
 ('Aston Villa', 1114, 392, 311, 411, 1392, 1460, -68, 1487),
 ('West Ham United', 1072, 360, 270, 442, 1337, 1558, -221, 1350),
 ('Southampton', 924, 280, 248, 396, 1114, 1355, -241, 1088),
 ('Blackburn Rovers', 696, 262, 184, 250, 927, 907, 20, 970),
 ('Leicester City', 650, 218, 167, 265, 871, 936, -65, 821),
 ('Leeds United', 582, 223, 151, 208, 793, 784, 9, 820),
 ('Fulham', 646, 190, 169, 287, 741, 945, -204, 739),
 ('Middlesbrough', 574, 165, 169, 240, 648, 794, -146, 661),
 ('Crystal Palace', 578, 169, 151, 258, 644, 833, -189, 658),
 ('Sunderland', 608, 153, 159, 296, 612, 904, -292, 618),
 ('Bolton Wanderers', 494, 149, 128, 217, 575, 745, -170, 575),
 ('West Bromwich Albion', 494, 117, 139, 238, 510, 772, -262, 490),
 ('Stoke City', 380, 116, 109, 155, 398, 525, -127, 457),
 ('Wolverhampton Wanderers', 380, 114, 93, 173, 409, 585, -176, 435),
 ('Coventry City', 354, 99, 112, 143, 387, 490, -103, 409),
 ('Norwich City', 392, 99, 105, 188, 414, 669, -255, 402),
 ('Sheffield Wednesday', 316, 101, 89, 126, 409, 453, -44, 392),
 ('Wimbledon', 316, 99, 94, 123, 384, 472, -88, 391),
 ('Charlton Ath', 304, 93, 82, 129, 342, 442, -100, 361),
 ('Burnley', 342, 88, 85, 169, 341, 533, -192, 349),
 ('Wigan Athletic', 304, 85, 76, 143, 316, 482, -166, 331),
 ('Brighton & Hove Albion', 266, 78, 85, 103, 317, 373, -56, 319),
 ('Swansea City', 266, 82, 66, 118, 306, 383, -77, 312),
 ('Nottingham Forest', 274, 78, 79, 117, 316, 422, -106, 309),
 ('Queens Park Rangers', 278, 81, 65, 132, 339, 431, -92, 308),
 ('Birmingham City', 266, 73, 82, 111, 273, 360, -87, 301),
 ('Bournemouth', 266, 80, 58, 128, 332, 468, -136, 298),
 ('Portsmouth', 266, 79, 65, 122, 292, 380, -88, 293),
 ('Watford', 304, 73, 66, 165, 310, 518, -208, 285),
 ('Derby County', 266, 68, 70, 128, 271, 420, -149, 274),
 ('Sheffield United', 236, 56, 57, 123, 222, 374, -152, 225),
 ('Ipswich Town', 202, 57, 53, 92, 219, 312, -93, 224),
 ('Hull City', 190, 41, 48, 101, 181, 323, -142, 171),
 ('Brentford', 114, 38, 30, 46, 162, 167, -5, 144),
 ('Reading', 114, 32, 23, 59, 136, 186, -50, 119),
 ('Oldham Athletic', 84, 22, 23, 39, 105, 142, -37, 89),
 ('Cardiff City', 76, 17, 13, 46, 66, 143, -77, 64),
 ('Bradford City', 76, 14, 20, 42, 68, 138, -70, 62),
 ('Huddersfield', 76, 12, 17, 47, 50, 134, -84, 53),
 ('Blackpool', 38, 10, 9, 19, 55, 78, -23, 39),
 ('Barnsley', 38, 10, 5, 23, 37, 82, -45, 35),
 ('Swindon Town', 42, 5, 15, 22, 47, 100, -53, 30),
 ('Luton Town', 38, 6, 8, 24, 52, 85, -33, 26)]